- name: Install various packages
  package:
    name: 
      - ca-certificates 
      - curl 
      - gnupg 
      - lsb-release
      - curl
    state: present
  become: true

    
- name: Install Docker
  command: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
  become: true
