- name: Google Chrome version
  command: google-chrome --version
  changed_when: false
  failed_when: false
  register: chrome_version

- name: Install Google Chrome
  block:
  - name: Download Google Chrome
    get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /tmp/
  
  - name: Install Google Chrome
    apt:
      deb: /tmp/google-chrome-stable_current_amd64.deb
    become: true
  when: chrome_version.rc != 0
