- name: Check lazygit version
  command: lazygit --version
  changed_when: false
  failed_when: false
  register: lazygit_version
    
- name: Install lazygit
  block:
  - name: Download lazygit
    get_url:
      url: https://github.com/jesseduffield/lazygit/releases/download/v0.34/lazygit_0.34_Linux_x86_64.tar.gz
      dest: /tmp/
  
  - name: Unarchive lazygit
    unarchive:
      src: /tmp/lazygit_0.34_Linux_x86_64.tar.gz
      dest: /usr/local/bin/
    become: true
  when: lazygit_version.rc != 0 or "0.34" not in lazygit_version.stdout
