- name: Check neovim installation
  command: nvim --version
  changed_when: false
  failed_when: false
  register: nvim_version

- name: Install neovim
  block:
    - name: Download neovim
      get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.tar.gz
        dest: /tmp/
    
    - name: Unarchive install
      unarchive:
        src: /tmp/nvim-linux64.tar.gz
        dest: ~/.programs/
    
    - name: Symlink nvim
      file:
        src: ~/.programs/nvim-linux64/bin/nvim
        dest: ~/.local/bin/nvim
        state: link

  when: nvim_version.rc != 0 or "0.7.0" not in nvim_version.stdout
