- name: Install various packages
  package:
    name: 
      - git
      - vim
      - ansible
      - zsh
      - nodejs
      - npm
      - cargo
      - pip
    state: present
  become: true

- name: Create .npm-global
  file:
    path: ~/.npm-global
    state: directory

- name: Set npm prefix
  command: npm config set prefix ~/.npm-global

- name: Git config
  command: git config --global user.email 'tajpereira@gmail.com'

- name: Git config
  command: git config --global user.name 'Taj Pereira'

