- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    depth: 1
    dest: ~/powerlevel10k

- name: Copy zshrc
  copy:
    src: .zshrc
    dest: ~/.zshrc

- name: Set login shell of user {{ ansible_env.USER }} to `/bin/zsh` with `usermod`
  ansible.builtin.command: usermod --shell /bin/zsh {{ ansible_env.USER }}
  become: true
  changed_when: false
